from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PanelField:
    key: str
    label: str
    default: float | int | bool | str = 0


_PANEL_FIELD_DESCRIPTIONS: dict[str, str] = {
    "engine_rpm": "Rotacao atual do motor em RPM.",
    "current_gear": "Marcha atual do veiculo. Re costuma ser negativa, neutro e zero.",
    "speed": "Velocidade atual do veiculo ja convertida para a unidade escolhida.",
    "water_temperature": "Temperatura principal do motor ou liquido de arrefecimento.",
    "temperature_warning": "Alerta de superaquecimento enviado pelo jogo.",
    "pressure": "Pressao principal enviada pelo jogo ou plugin.",
    "air_pressure_emergency": "Indica estado critico de pressao de ar.",
    "air_pressure_warning": "Indica alerta de pressao de ar baixa.",
    "cruise_control": "Mostra se o piloto automatico ou controle de cruzeiro esta ligado.",
    "wipers": "Estado basico dos limpadores quando o plugin expor esse campo.",
    "park_brake": "Freio de estacionamento ou freio de mao.",
    "motor_brake": "Freio motor.",
    "electric_enabled": "Indica se a parte eletrica do veiculo esta ativa.",
    "engine_enabled": "Indica se o motor esta ligado.",
    "blinker_left_active": "Pisca esquerdo em funcionamento visivel.",
    "blinker_right_active": "Pisca direito em funcionamento visivel.",
    "blinker_left_enabled": "Pisca esquerdo selecionado ou armado no veiculo.",
    "blinker_right_enabled": "Pisca direito selecionado ou armado no veiculo.",
    "rotation_x": "Rotacao no eixo X.",
    "rotation_y": "Rotacao no eixo Y.",
    "rotation_z": "Rotacao no eixo Z.",
    "acceleration_x": "Aceleracao no eixo X.",
    "acceleration_y": "Aceleracao no eixo Y.",
    "acceleration_z": "Aceleracao no eixo Z.",
    "map_position_x": "Posicao no mapa no eixo X.",
    "map_position_y": "Posicao no mapa no eixo Y.",
    "map_position_z": "Posicao no mapa no eixo Z.",
    "lights_parking": "Luzes de posicao ou estacionamento.",
    "lights_low_beam": "Farol baixo.",
    "lights_high_beam": "Farol alto.",
    "battery_voltage_warning": "Alerta de baixa tensao da bateria.",
    "air_warning": "Aviso geral relacionado a ar ou pressao pneumatica.",
    "air_emergency": "Emergencia relacionada a sistema de ar.",
    "adblue_warning": "Aviso de AdBlue/DEF baixo.",
    "oil_warning": "Aviso de oleo.",
    "water_warning": "Aviso de agua ou arrefecimento.",
    "damage_info": "Valor bruto de dano informado pelo plugin.",
    "mechanical_damage": "Dano mecanico do veiculo.",
    "vehicle_damage": "Dano geral do veiculo.",
    "fuel_percent": "Combustivel em porcentagem.",
    "fuel_avg_consumption": "Consumo medio de combustivel.",
    "clutch": "Posicao da embreagem.",
    "brake": "Intensidade do freio.",
    "throttle": "Intensidade do acelerador.",
    "turbo": "Pressao ou atividade do turbo.",
    "traction_control": "Controle de tracao.",
    "abs": "Sistema ABS ativo.",
    "oil_pressure": "Pressao do oleo.",
    "oil_temperature": "Temperatura do oleo.",
    "hazard_warning_lights": "Pisca-alerta.",
    "blinker_left_relay": "Estado do rele do pisca esquerdo.",
    "blinker_right_relay": "Estado do rele do pisca direito.",
    "connected": "Indica se o DSW esta recebendo telemetria valida nesse momento.",
    "driving_vehicle": "Indica se o jogador esta realmente dentro/controlando um veiculo.",
    "wear_percent": "Desgaste do veiculo ou equipamento.",
    "operation_time_minutes": "Tempo de uso acumulado em minutos.",
    "fuel_current": "Quantidade atual de combustivel.",
    "fuel_capacity": "Capacidade maxima do reservatorio principal.",
    "fuel_type_code": "Codigo do tipo de combustivel identificado pelo plugin.",
    "engine_rpm_min": "RPM minimo do motor.",
    "engine_rpm_max": "RPM maximo do motor.",
    "cruise_control_speed": "Velocidade alvo atual do controle de cruzeiro.",
    "cruise_control_max_speed": "Velocidade maxima configurada para o controle de cruzeiro.",
    "ai_active": "Mostra se uma IA ou helper esta controlando o veiculo.",
    "reverse_driving": "Indica deslocamento em re.",
    "motor_fan_enabled": "Estado da ventoinha do motor.",
    "vehicle_price": "Preco de compra do veiculo.",
    "vehicle_sell_price": "Preco de venda do veiculo.",
    "honk_on": "Buzina ativa.",
    "beacon_on": "Giroflex ou luz de baliza ativa.",
    "hazard_on": "Pisca-alerta ativo.",
    "wipers_on": "Limpadores ativos.",
    "angle_rotation": "Angulo de orientacao do veiculo.",
    "mass": "Massa do veiculo principal.",
    "total_mass": "Massa total incluindo implementos/carga.",
    "on_field": "Indica se o veiculo esta sobre um campo.",
    "def_level": "Nivel atual de DEF/AdBlue.",
    "def_capacity": "Capacidade maxima de DEF/AdBlue.",
    "air_level": "Nivel atual de ar do sistema.",
    "air_capacity": "Capacidade maxima do sistema de ar.",
    "money": "Dinheiro atual do jogo ou fazenda.",
    "temperature_min": "Temperatura minima do ambiente.",
    "temperature_max": "Temperatura maxima do ambiente.",
    "temperature_trend_code": "Tendencia da temperatura ambiente em forma numerica.",
    "day_time_minutes": "Hora do dia em minutos.",
    "weather_current_code": "Codigo numerico do clima atual.",
    "weather_next_code": "Codigo numerico da proxima previsao de clima.",
    "current_day": "Dia atual do save ou sessao.",
    "game_edition_code": "Edicao do jogo identificada pelo plugin.",
    "implements_count": "Quantidade total de implementos detectados.",
    "implements_lowered_count": "Quantos implementos estao abaixados.",
    "implements_selected_count": "Quantos implementos estao selecionados.",
    "implements_turned_on_count": "Quantos implementos estao ligados.",
    "implements_avg_wear": "Desgaste medio dos implementos detectados.",
    "raw_speed": "Velocidade bruta recebida antes de ajustes.",
    "raw_gear": "Marcha bruta recebida antes de normalizacao.",
    "lap_number": "Numero atual da volta, etapa ou passagem reportada pela telemetria.",
    "best_lap_time": "Melhor tempo de volta conhecido pela sessao.",
    "last_lap_time": "Tempo registrado na ultima volta concluida.",
    "current_lap_time": "Tempo parcial da volta ou etapa atual.",
    "race_position": "Posicao atual do jogador na corrida ou classificacao.",
    "race_time": "Tempo total acumulado da sessao ou prova.",
    "distance_traveled": "Distancia total percorrida pelo veiculo.",
    "steering": "Posicao do volante ou entrada de direcao normalizada.",
    "engine_max_rpm": "RPM maximo informado pela telemetria.",
    "power_kw": "Potencia instantanea em quilowatts.",
    "torque_nm": "Torque instantaneo em newton-metro.",
    "velocity_x": "Velocidade no eixo X.",
    "velocity_y": "Velocidade no eixo Y.",
    "velocity_z": "Velocidade no eixo Z.",
}


def panel_field_description(key: str, label: str) -> str:
    if key in _PANEL_FIELD_DESCRIPTIONS:
        return _PANEL_FIELD_DESCRIPTIONS[key]

    prefixes = {
        "implements_position_": "Posicao logica do implemento no slot {slot}.",
        "implements_lowered_": "Indica se o implemento do slot {slot} esta abaixado.",
        "implements_selected_": "Indica se o implemento do slot {slot} esta selecionado.",
        "implements_turned_on_": "Indica se o implemento do slot {slot} esta ligado.",
        "implements_wear_": "Desgaste do implemento no slot {slot}.",
    }
    for prefix, template in prefixes.items():
        if key.startswith(prefix):
            return template.format(slot=key.removeprefix(prefix))
    return f"{label}. Variavel exposta pelo plugin selecionado."


PANEL_FIELDS: tuple[PanelField, ...] = (
    PanelField("engine_rpm", "RPM"),
    PanelField("current_gear", "Current gear"),
    PanelField("speed", "Speed"),
    PanelField("water_temperature", "Water temperature"),
    PanelField("temperature_warning", "Temperature warning", False),
    PanelField("pressure", "Pressure"),
    PanelField("air_pressure_emergency", "Air Pressure emergency", False),
    PanelField("air_pressure_warning", "Air Pressure warning", False),
    PanelField("cruise_control", "Cruise Control", False),
    PanelField("wipers", "Wipers", False),
    PanelField("park_brake", "Park Brake", False),
    PanelField("motor_brake", "Motor Brake", False),
    PanelField("electric_enabled", "Electric Enabled", False),
    PanelField("engine_enabled", "Engine Enabled", False),
    PanelField("blinker_left_active", "Blinker Left Active", False),
    PanelField("blinker_right_active", "Blinker Right Active", False),
    PanelField("blinker_left_enabled", "Blinker Left Enabled", False),
    PanelField("blinker_right_enabled", "Blinker Right Enabled", False),
    PanelField("rotation_x", "Rotation X"),
    PanelField("rotation_y", "Rotation Y"),
    PanelField("rotation_z", "Rotation Z"),
    PanelField("acceleration_x", "Acceleration X"),
    PanelField("acceleration_y", "Acceleration Y"),
    PanelField("acceleration_z", "Acceleration Z"),
    PanelField("map_position_x", "Map position X"),
    PanelField("map_position_y", "Map position Y"),
    PanelField("map_position_z", "Map position Z"),
    PanelField("lights_parking", "Lights Parking", False),
    PanelField("lights_low_beam", "Lights Beam Low", False),
    PanelField("lights_high_beam", "Lights Beam High", False),
    PanelField("battery_voltage_warning", "Battery Voltage Warning", False),
    PanelField("air_warning", "Air-Warning", False),
    PanelField("air_emergency", "Air-Emergency", False),
    PanelField("adblue_warning", "Adblue Warning", False),
    PanelField("oil_warning", "Oil-Warning", False),
    PanelField("water_warning", "Water-Warning", False),
    PanelField("damage_info", "damage info"),
    PanelField("mechanical_damage", "mechanical damage"),
    PanelField("vehicle_damage", "vehicle damage"),
    PanelField("fuel_percent", "FUEL (per %)"),
    PanelField("fuel_avg_consumption", "fuelAvgConsumption"),
    PanelField("clutch", "clutch"),
    PanelField("brake", "brake"),
    PanelField("throttle", "throttle"),
    PanelField("steering", "Steering"),
    PanelField("turbo", "TURBO"),
    PanelField("traction_control", "CT"),
    PanelField("abs", "ABS"),
    PanelField("oil_pressure", "OIL-Pressure"),
    PanelField("oil_temperature", "OIL temp"),
    PanelField("hazard_warning_lights", "hazard warning lights", False),
    PanelField("blinker_left_relay", "Blinker Left relay", False),
    PanelField("blinker_right_relay", "Blinker Right relay", False),
    PanelField("connected", "Connected", False),
    PanelField("driving_vehicle", "Driving vehicle", False),
    PanelField("wear_percent", "Wear percent"),
    PanelField("operation_time_minutes", "Operation time minutes"),
    PanelField("fuel_current", "Fuel current"),
    PanelField("fuel_capacity", "Fuel capacity"),
    PanelField("fuel_type_code", "Fuel type code"),
    PanelField("engine_rpm_min", "Engine RPM min"),
    PanelField("engine_rpm_max", "Engine RPM max"),
    PanelField("cruise_control_speed", "Cruise control speed"),
    PanelField("cruise_control_max_speed", "Cruise control max speed"),
    PanelField("ai_active", "AI active", False),
    PanelField("reverse_driving", "Reverse driving", False),
    PanelField("motor_fan_enabled", "Motor fan enabled", False),
    PanelField("vehicle_price", "Vehicle price"),
    PanelField("vehicle_sell_price", "Vehicle sell price"),
    PanelField("honk_on", "Honk on", False),
    PanelField("beacon_on", "Beacon on", False),
    PanelField("hazard_on", "Hazard on", False),
    PanelField("wipers_on", "Wipers on", False),
    PanelField("angle_rotation", "Angle rotation"),
    PanelField("mass", "Mass"),
    PanelField("total_mass", "Total mass"),
    PanelField("on_field", "On field", False),
    PanelField("def_level", "DEF level"),
    PanelField("def_capacity", "DEF capacity"),
    PanelField("air_level", "Air level"),
    PanelField("air_capacity", "Air capacity"),
    PanelField("money", "Money"),
    PanelField("temperature_min", "Temperature min"),
    PanelField("temperature_max", "Temperature max"),
    PanelField("temperature_trend_code", "Temperature trend code"),
    PanelField("day_time_minutes", "Day time minutes"),
    PanelField("weather_current_code", "Weather current code"),
    PanelField("weather_next_code", "Weather next code"),
    PanelField("current_day", "Current day"),
    PanelField("game_edition_code", "Game edition code"),
    PanelField("lap_number", "Lap number"),
    PanelField("best_lap_time", "Best lap time"),
    PanelField("last_lap_time", "Last lap time"),
    PanelField("current_lap_time", "Current lap time"),
    PanelField("race_position", "Race position"),
    PanelField("race_time", "Race time"),
    PanelField("distance_traveled", "Distance traveled"),
    PanelField("engine_max_rpm", "Engine RPM max current"),
    PanelField("power_kw", "Power kW"),
    PanelField("torque_nm", "Torque Nm"),
    PanelField("velocity_x", "Velocity X"),
    PanelField("velocity_y", "Velocity Y"),
    PanelField("velocity_z", "Velocity Z"),
    PanelField("implements_count", "Implements count"),
    PanelField("implements_lowered_count", "Implements lowered count"),
    PanelField("implements_selected_count", "Implements selected count"),
    PanelField("implements_turned_on_count", "Implements turned on count"),
    PanelField("implements_avg_wear", "Implements avg wear"),
    PanelField("implements_position_1", "Implement position 1"),
    PanelField("implements_position_2", "Implement position 2"),
    PanelField("implements_position_3", "Implement position 3"),
    PanelField("implements_position_4", "Implement position 4"),
    PanelField("implements_position_5", "Implement position 5"),
    PanelField("implements_position_6", "Implement position 6"),
    PanelField("implements_position_7", "Implement position 7"),
    PanelField("implements_position_8", "Implement position 8"),
    PanelField("implements_position_9", "Implement position 9"),
    PanelField("implements_position_10", "Implement position 10"),
    PanelField("implements_lowered_1", "Implement lowered 1", False),
    PanelField("implements_lowered_2", "Implement lowered 2", False),
    PanelField("implements_lowered_3", "Implement lowered 3", False),
    PanelField("implements_lowered_4", "Implement lowered 4", False),
    PanelField("implements_lowered_5", "Implement lowered 5", False),
    PanelField("implements_lowered_6", "Implement lowered 6", False),
    PanelField("implements_lowered_7", "Implement lowered 7", False),
    PanelField("implements_lowered_8", "Implement lowered 8", False),
    PanelField("implements_lowered_9", "Implement lowered 9", False),
    PanelField("implements_lowered_10", "Implement lowered 10", False),
    PanelField("implements_selected_1", "Implement selected 1", False),
    PanelField("implements_selected_2", "Implement selected 2", False),
    PanelField("implements_selected_3", "Implement selected 3", False),
    PanelField("implements_selected_4", "Implement selected 4", False),
    PanelField("implements_selected_5", "Implement selected 5", False),
    PanelField("implements_selected_6", "Implement selected 6", False),
    PanelField("implements_selected_7", "Implement selected 7", False),
    PanelField("implements_selected_8", "Implement selected 8", False),
    PanelField("implements_selected_9", "Implement selected 9", False),
    PanelField("implements_selected_10", "Implement selected 10", False),
    PanelField("implements_turned_on_1", "Implement turned on 1", False),
    PanelField("implements_turned_on_2", "Implement turned on 2", False),
    PanelField("implements_turned_on_3", "Implement turned on 3", False),
    PanelField("implements_turned_on_4", "Implement turned on 4", False),
    PanelField("implements_turned_on_5", "Implement turned on 5", False),
    PanelField("implements_turned_on_6", "Implement turned on 6", False),
    PanelField("implements_turned_on_7", "Implement turned on 7", False),
    PanelField("implements_turned_on_8", "Implement turned on 8", False),
    PanelField("implements_turned_on_9", "Implement turned on 9", False),
    PanelField("implements_turned_on_10", "Implement turned on 10", False),
    PanelField("implements_wear_1", "Implement wear 1"),
    PanelField("implements_wear_2", "Implement wear 2"),
    PanelField("implements_wear_3", "Implement wear 3"),
    PanelField("implements_wear_4", "Implement wear 4"),
    PanelField("implements_wear_5", "Implement wear 5"),
    PanelField("implements_wear_6", "Implement wear 6"),
    PanelField("implements_wear_7", "Implement wear 7"),
    PanelField("implements_wear_8", "Implement wear 8"),
    PanelField("implements_wear_9", "Implement wear 9"),
    PanelField("implements_wear_10", "Implement wear 10"),
)

PANEL_FIELD_KEYS = [field.key for field in PANEL_FIELDS]
PANEL_FIELDS_BY_KEY = {field.key: field for field in PANEL_FIELDS}
PANEL_LABEL_TO_KEY = {field.label: field.key for field in PANEL_FIELDS}

DEFAULT_PANEL_ORDER = [
    "engine_rpm",
    "current_gear",
    "speed",
    "water_temperature",
    "temperature_warning",
    "pressure",
    "air_pressure_emergency",
    "air_pressure_warning",
    "cruise_control",
    "wipers",
    "park_brake",
    "motor_brake",
    "electric_enabled",
    "engine_enabled",
    "blinker_left_active",
    "blinker_right_active",
    "rotation_x",
    "rotation_y",
    "rotation_z",
    "acceleration_x",
]
